server {
    listen 443 ssl;
    server_name ~^dev-(?<subport>\d+)\.khai\.io;
    server_tokens off;

    ssl_certificate     /etc/letsencrypt/live/khai.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/khai.io/privkey.pem;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    resolver 8.8.8.8 8.8.4.4 valid=300s;
    resolver_timeout 5s;

    client_max_body_size 20M;

    add_header Strict-Transport-Security "max-age=63072000; includeSubdomains";
    # add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";

    location / {
        # proxy stuff
        proxy_pass_request_headers on;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        Host dev-$subport.khai.io;
        proxy_redirect          off;
        proxy_pass              http://127.0.0.1:$subport;
        proxy_set_header        X-Forwarded-Proto $scheme;
    }
}
